openapi: 3.0.1
info:
  title: Som Energia Infoenergia API
  description: 'API for exchange contract information'
  termsOfService: https://www.somenergia.coop/ca/avis-legal/
  contact:
    email: it@somenergia.coop
  license:
    name: AGPL-3.0
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
  version: 0.0.0
externalDocs:
  description: ''
  url: ''
servers:
- url: https://infoenergia-api.somenergia.coop/
tags:
- name: contracts
  description: All information about a contract
- name: modcontracts
  description: All information about contract modifications
- name: measurements
  description: All information about contract energy measurements
paths:
  /user/login:
    post:
      tags:
      - user
      summary: Logs user into the system
      operationId: server.basic_auth
      parameters:
      - name: username
        in: query
        description: The user name for login
        required: true
        schema:
          type: string
      - name: password
        in: query
        description: The password for login in clear text
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: string
        400:
          description: Invalid username/password supplied
          content: {}
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        token:
          type: string
        active:
          type: boolean

  securitySchemes:
    infoenergia_auth:
      type: http
      scheme: basic
      x-basicInfoFunc: app.basic_auth
